# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths-ignore:
    # Ignore CODE_METRICS.md and README.md files
    - '**.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    permissions:
        contents: write
        pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.101'
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
      - run: dotnet publish ./Pierre.Fontaine.Ocr.Console/Pierre.Fontaine.Ocr.Console.csproj --self-contained true --output ./win-x64/ocr -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
      - name: Upload WebApp1 Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publish win-x64 Ocr
          path: ./win-x64/ocr
      # Analyze repositories source metrics:
      # Create (or update) CODE_METRICS.md file.
      - name: .NET code metrics
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './github-actions/DotNet.GitHubAction' }}

      # Create a pull request if there are changes.
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.4.1
        if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics }} == 'true'
        with:
          title: '${{ steps.dotnet-code-metrics.outputs.summary-title }}'
          body: '${{ steps.dotnet-code-metrics.outputs.summary-details }}'
          commit-message: '.NET code metrics, automated pull request.'
